#define HOSTNAME "localhost"
#define ALICE_PORT 8001
#define BOB_PORT 8006

#define REQUESTED_LENGTH 40
#define MAX_QUBITS 10

#define ALICE_CLASS_PORT "8080"
#define BOB_CLASS_PORT "8081"

#define CLASS_MSG_HELLO 1